/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable react/jsx-no-comment-textnodes */
import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Header } from '../../components/Header'
import { SideBarMenu } from '../../components/SidebarMenu'

const Profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <div>
        <div className="leftSide">
          <SideBarMenu />
        </div>
        <div className="content">Profile</div>
        <div className="rightSide"></div>
      </div>
    </div>
  )
}

export default Profile
