/* eslint-disable @next/next/no-page-custom-font */
import type { AppProps } from 'next/app'
import { theme } from '../theme'
import { ThemeProvider } from '@material-ui/core'
import '../styles/globals.css'
import Head from 'next/head'
import 'macro-css'
import { wrapper } from '../redux/store'
import { setuserData } from '../redux/slices/user'
import { Api } from '../utils/api'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ThemeProvider theme={theme}>
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  )
}

MyApp.getInitialProps = wrapper.getInitialAppProps((store) => async ({ ctx, Component }) => {
  try {
    const userData = await Api(ctx).user.getMe()
    store.dispatch(setuserData(userData))
  } catch (error) {
    if (ctx.asPath === '/write') {
      ctx.res?.writeHead(302, {
        Location: '/403',
      })
      ctx.res?.end()
    }

    console.log(error)
  }

  return {
    pageProps: {
      ...(Component.getInitialProps ? await Component.getInitialProps({ ...ctx, store }) : {}),
    },
  }
})

export default wrapper.withRedux(MyApp)
