/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable react/jsx-no-comment-textnodes */
import { Paper, Typography } from '@material-ui/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <div>
        <div className="leftSide"></div>
        <div className="content">
          <Paper elevation={0} className="p-20">
            <Typography variant="h5">19 August, Thursday</Typography>
            <Typography className="mt-15 mb-15">Some text here</Typography>
            <Image
              width={640}
              height={427}
              src="https://nypost.com/wp-content/uploads/sites/2/2022/03/Space-sex-feature.jpg?quality=75&strip=all"
              alt=""
            />
          </Paper>
        </div>
        <div className="rightSide"></div>
      </div>
    </div>
  )
}

export default Home
